### ISSUE TITLE
Add saveMany to CombinedTransaction

### ISSUE THREAD

**Issue by jelsy2004** [compositephp/db#5]
Hello there! I've been using your DB helper and it looks very interesting. I have a suggestion that might make it even better.
`Composite\DB\CombinedTransaction` has a `save()` method, but not `saveMany()`.
It would be useful to have the ability to save multiple entities at one time, making it more efficient.

**Comment by compositephp** [comment]
Good idea will do it

**Comment by compositephp** [comment]
Its done in 0.4.0
