### ISSUE TITLE
Migrations - Does CompositeDB create table schemas?

### ISSUE THREAD

**Issue by tno2007** [compositephp/db#7]
Question:

### Short version:
Can CompositeDB create tables and table schemas?

### Long version

In the readme, you specify...

```md
It also has many popular features such as:
- Migrations - synchronise your php entities with database tables
```

I also followed the migration guide here:
https://github.com/compositephp/db/blob/master/doc/migrations.md

Following that guide, I can generate a TableClass from a Class.

```sh
php cli.php composite:generate-table 'App\Application\Contact' 
```
*(Small sidenote, the connection_name parameter does not work, as specified in the guide)*
```
php cli.php composite:generate-table connection_name TableName 'App\Models\EntityName'
```

But when I run sample code, but the database is not being updated.

The error complains the table could not be found.
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'compositedb.Contact' doesn't exist in ....
```

Sample project is here:
https://github.com/tno2007/composite-db-generate-tables

It does not seems like Composite does not create any tables, so I just want to confirm, can CompositeDB create tables and table schemas?

**Comment by compositephp** [comment]
Hi there!

Yes, sorry I fixed the "copypasta" mistake in the documentation about using "composite:generate-table" command.
Thanks for the report!

Regaring your main question:
> Can CompositeDB create tables and table schemas?

The answer is yes, Composite DB supports migrations with automatic schema generation.
To do this please apply the next diff to your project:

```
diff --git a/cli.php b/cli.php
index ce0fef7..e1159c7 100644
--- a/cli.php
+++ b/cli.php
@@ -8,10 +8,14 @@ use Symfony\Component\Console\Application;
 
 //may be changed with .env file
 putenv('CONNECTIONS_CONFIG_FILE=./config.php');
+putenv('ENTITIES_DIR=./src');
+putenv('MIGRATIONS_DIR=./src/Migrations');
+putenv('MIGRATIONS_NAMESPACE=App\Migrations');
 
 $app = new Application();
 $app->addCommands([
      new Commands\GenerateEntityCommand(),
      new Commands\GenerateTableCommand(),
+     new Commands\MigrateCommand(),
 ]);
 $app->run();
\ No newline at end of file
diff --git a/src/Migrations/.gitkeep b/src/Migrations/.gitkeep
new file mode 100644
index 0000000..e69de29

```

And then call `php cli.php composite:migrate` twice. 
The first will generate migration files and the second will execute them.

After that, you can generate table class with command `php cli.php composite:generate-table 'App\Application\Contact' `

**Comment by compositephp** [comment]
And yes, it's a significant oversight that the documentation lacks this information; I'll definitely add it soon.

**Comment by tno2007** [comment]
Your instructions worked perfectly!
Thanks for your assistance.
